export * from "./dashboard";
export * from "./users";
export * from "./settings";
export * from "./documents";
export * from "./home";
export * from "./login";
export * from "./register";
export * from "./forgot-password";
export * from "./404";
